import { Job } from '../classes/job';

export const JOBS: Job[] = [
  { id: 1, 
    company: 'Clayton Homes', 
    start: 'February 2009', 
    end: 'January 2020', 
    title: 'Account Specialist / Front End Developer',
    details: [
    'Quality assurance to see that code matches design, intent, and accessibility',
    'Converting PSD compositions into HTML and CSS',
    'Expanding webpage functionality using JavaScript/JQuery/React JS',
    'Knowledgeable about cross-browser issues and testing',
    'Code pages to match customer requirements',
    'Write reusable code for UI components',
    'Utilize existing standards to maximize browser compatibility',
    'Building and testing responsive layouts',
    'Given 10+ ACE awards for excellence',
    'Managed a large base of 900+ mortgage loan account customers',
    '100+ calls per day to counsel customers with past-due mortgage accounts to arrange payments or assist them in bringing accounts up to date',
    'Recommended alternative mortgage payment options',
    'Maintained strict compliance with regulations',
    'Mentoring several newer employees',
    'Earned recognition for achieving a 95% average score for call handling and customer service ability'
  ] },
  { id: 2, 
    company: 'StoragePug', 
    start: 'March 2020', 
    end: 'November 2021',
    title: 'Junior Web Developer / Website Specialist', 
    details: [
    'Train others on design standards and using specialized CMS',
    'Converting Zeplin and Figma compositions into HTML and SCSS',
    'Build components using Angular for specialized CMS',
    'Expertly edit images to more closely meet design standards using PhotoShop',
    'Utilize provided wireframes, prototypes and content to build websites to design standards using a specialized CMS',
    'Ensure work adheres to established standards and practices',
    'Use drag-and-drop web editor to build self-storage websites',
    'Utilize CSS/HTML to override CMS settings to meet design requirements',
    'Use drag-and-drop web editor to build self-storage websites',
    'Communicate with team members, developers, and designers as needed during the website building process',
    'Present designs to peers',
    'Showcase what makes each client awesome and help them book more units through their website'
  ] },
];